### PR TITLE
[FIX] Problem parsing string to array

### LINKED ISSUE #32: Array string parse to string
When pass fiels empty array as param on get method it return an error, cause the property has been declared as array but we introduce a string value.
Check here: 
https://github.com/bim-g/Wepesi-ORM/blob/master/src/DB_Select.php#L127-L129

### PR DESCRIPTION
**Pull request by bim-g**
There is a problem while trying to get data from table with a empy filed array it generate error parsing, cause the field param as been declare as array then it can not take string value.
closes #32

### CODE REVIEW

File: src/DB_Select.php [hunk 1]
```diff
@@ -39,7 +39,8 @@ function __construct(\PDO $pdo, string $table, string $action = null)
         $this->_pdo = $pdo;
         $this->action = $action;
         $this->_dsc = $this->_asc = "";
-        $this->_where = $this->_fields =[];
+        $this->_where =[];
+        $this->_fields =['keys' => '*'];
```
Comment (bim-g) [inline src/DB_Select.php:43]: Dind expect it will cause an error

Comment (bim-g) [reply src/DB_Select.php:43]: Fixed
