### PR TITLE
[FIX] seclect ASC and DESC not workin fine

### LINKED ISSUE #27: ASC and DESC are not workin
When apply ASC or DESC nothing happen. it sems it does not reponsd to any thing.

### PR DESCRIPTION
**Pull request by bim-g**
closes #27

### CODE REVIEW

File: src/DB_Select.php [hunk 1]
```diff
@@ -202,9 +212,7 @@ private function select(): array
         $WHERE = $this->_where['field'] ?? '';
         $params = $this->_where['value'] ?? [];
         //
-        $sortedASC_DESC = ($this->_dsc || $this->_asc) ? ($this->_dsc ?? $this->_asc) : null;
-        //
-        $sql = "SELECT " . $fields . " FROM " . " $this->table " . $WHERE . $this->groupBY . $this->orderBy . $sortedASC_DESC . $this->_limit . $this->_offset;
+        $sql = "SELECT " . $fields . " FROM " . " $this->table " . $WHERE . $this->groupBY . $this->orderBy . $this->_dsc . $this->_asc . $this->_limit . $this->_offset;
```
Comment (bim-g) [inline src/DB_Select.php:215]: Make order by ASC or RESC work fine

**Review by bim-g — COMMENTED** [review]
No work fine
