### PR TITLE
[FIX] Insert return `-1` as lastID

### LINKED ISSUE #21: Insert last I'd return -1
While insert new information everything work fine but, when try to get last I'd it return -1 unless information has been - saved.

### PR DESCRIPTION
**Pull request by bim-g**
When insert a new record, and we want to get the last id from `lastid` it return `-1` instea of returning the id of the las record.
closes #21

### CODE REVIEW

File: src/DB.php [hunk 1]
```diff
@@ -143,7 +142,7 @@ function query($sql, array $params = []): DB
         $this->_results = $q['result'];
         $this->_count = $q['count'];
         $this->_error = $q['error'];
-        $this->_lastID = $q['lastID'];
+        $this->_lastID = $q['lastID']??-1;
```
Comment (bim-g) [inline src/DB.php:145]: manage lastid value

File: src/DB_Insert.php [hunk 2]
```diff
@@ -7,7 +7,9 @@
  */
 namespace Wepesi\App;
 
-class DB_Insert 
+use Wepesi\App\Traits\BuildQuery;
```
Comment (bim-g) [inline src/DB_Insert.php:10]: add builderQuery missing

File: src/DB_Select.php [hunk 3]
```diff
@@ -30,18 +30,18 @@ function __construct(\PDO $pdo, string $table, string $action = null)
         $this->action = $action;
         $this->_dsc = $this->_asc=null;
         $this->_where = $this->_fields =[];
-        $this->_error =null;
-        $this->orderBy = $this->groupBY =null;
-        $this->_limit = $this->_offset=null;
+        $this->_error = null;
+        $this->orderBy = $this->groupBY = null;
+        $this->_limit = $this->_offset = null;
+        $this->_join_comparison_sign = ['=', '>', '<', '!=', '<>'];
```
Comment (bim-g) [inline src/DB_Select.php:36]: instatiate join comparison on the constructor

**Review by bim-g — COMMENTED** [review]
Now insert work fine
