### PR TITLE
[UPD] fixed groupe by to pass a string as parameter

### LINKED ISSUE #19: unable to use groupe by
goupe by does not work problerly

### PR DESCRIPTION
**Pull request by bim-g**
closes #19

### CODE REVIEW

File: src/DB_Update.php [hunk 1]
```diff
@@ -125,11 +125,11 @@ function field(array $fields = []): DB_Update
      * @return $this
      * this module is use to execute sql request
      */
-    private function query($sql, array $params = []): DB_Update
+    private function query($sql, array $params = [])
     {
         $q = $this->executeQuery($this->_pdo, $sql, $params);
         $this->_results = $q['result'];
-        $this->_count = $q['count'];
+        $this->_count = $q['count']??0;
```
Comment (bim-g) [inline src/DB_Update.php:132]: return 0 in case there is no data

File: src/DB_Select.php [hunk 2]
```diff
@@ -214,7 +204,7 @@ private function select(): array
         //
         $sortedASC_DESC = ($this->_dsc || $this->_asc) ? ($this->_dsc ?? $this->_asc) : null;
         //
-        $sql = "SELECT {$fields} FROM {$this->table} " . $WHERE . $this->groupBY . $this->orderBy . $sortedASC_DESC . $this->_limit . $this->_offset;
+        $sql = "SELECT " . $fields . " FROM " . " $this->table " . $WHERE . $this->groupBY . $this->orderBy . $sortedASC_DESC . $this->_limit . $this->_offset;
```
Comment (bim-g) [inline src/DB_Select.php:207]: rewrite sele sql in better way

File: src/DB_Select.php [hunk 3]
```diff
@@ -43,16 +43,6 @@ function __construct(\PDO $pdo, string $table, string $action = null)
      */
     function where(array $params = [])
     {
-        // select where <> update where
```
Comment (bim-g) [inline src/DB_Select.php:46]: remove uselless comment

**Review by bim-g — COMMENTED** [review]
Refactor resolv select module
